blank_issues_enabled: true
contact_links:
  - name: Installation Help
    url: https://discord.gg/mnTJVSSaKp?utm_source=githubreadme&utm_medium=readme&utm_campaign=OSSLAUNCH&utm_id=OSSLAUNCH
    about: Please visit our Discord for help with your installation.
  - name: General Question
    url: https://discord.gg/mnTJVSSaKp?utm_source=githubreadme&utm_medium=readme&utm_campaign=OSSLAUNCH&utm_id=OSSLAUNCH
    about: Please visit our Discord for general questions about Pyrodactyl.
